name: Build app

on:
  push:
    branches:
      - "dev"
    paths:
      - "TimetableDesigner**"
  pull_request:
    branches:
      - "dev"
      - "main"
    paths:
      - "TimetableDesigner**"

jobs:
  analyze:
    name: Build app
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore