//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetableDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimetableDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string ClassroomEdit_Capacity {
            get {
                return ResourceManager.GetString("ClassroomEdit.Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is limited?.
        /// </summary>
        public static string ClassroomEdit_CapacityIsLimited {
            get {
                return ResourceManager.GetString("ClassroomEdit.CapacityIsLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ClassroomEdit_Description {
            get {
                return ResourceManager.GetString("ClassroomEdit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string ClassroomEdit_Groups_Basics {
            get {
                return ResourceManager.GetString("ClassroomEdit.Groups.Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string ClassroomEdit_Groups_Capacity {
            get {
                return ResourceManager.GetString("ClassroomEdit.Groups.Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClassroomEdit_Name {
            get {
                return ResourceManager.GetString("ClassroomEdit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During this class, other classes are taking place in this classroom.
        /// </summary>
        public static string Errors_ClassroomBusy {
            get {
                return ResourceManager.GetString("Errors.ClassroomBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class has no assigned classroom.
        /// </summary>
        public static string Errors_ClassroomNotAssigned {
            get {
                return ResourceManager.GetString("Errors.ClassroomNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During this class, group, to which selected subgroup is assigned, already has other classes.
        /// </summary>
        public static string Errors_GroupAllBusy {
            get {
                return ResourceManager.GetString("Errors.GroupAllBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During this class, the selected group already has other classes.
        /// </summary>
        public static string Errors_GroupBusy {
            get {
                return ResourceManager.GetString("Errors.GroupBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class has no assigned group.
        /// </summary>
        public static string Errors_GroupNotAssigned {
            get {
                return ResourceManager.GetString("Errors.GroupNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During this class, part of selected group already has other classes in subgroup.
        /// </summary>
        public static string Errors_GroupPartBusy {
            get {
                return ResourceManager.GetString("Errors.GroupPartBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class is not scheduled.
        /// </summary>
        public static string Errors_SlotNotAssigned {
            get {
                return ResourceManager.GetString("Errors.SlotNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During this class, the selected teacher conducts other classes.
        /// </summary>
        public static string Errors_TeacherBusy {
            get {
                return ResourceManager.GetString("Errors.TeacherBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class has no assigned teacher.
        /// </summary>
        public static string Errors_TeacherNotAssigned {
            get {
                return ResourceManager.GetString("Errors.TeacherNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected teacher is not available during the class.
        /// </summary>
        public static string Errors_TeacherNotAvailable {
            get {
                return ResourceManager.GetString("Errors.TeacherNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Global_AllFiles {
            get {
                return ResourceManager.GetString("Global.AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string Global_Classroom {
            get {
                return ResourceManager.GetString("Global.Classroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New classroom.
        /// </summary>
        public static string Global_DefaultClassroomName {
            get {
                return ResourceManager.GetString("Global.DefaultClassroomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string Global_DefaultGroupName {
            get {
                return ResourceManager.GetString("Global.DefaultGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string Global_DefaultProjectName {
            get {
                return ResourceManager.GetString("Global.DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New teacher.
        /// </summary>
        public static string Global_DefaultTeacherName {
            get {
                return ResourceManager.GetString("Global.DefaultTeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Global_Group {
            get {
                return ResourceManager.GetString("Global.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no project loaded.
        /// </summary>
        public static string Global_NoProjectLoadedTitle {
            get {
                return ResourceManager.GetString("Global.NoProjectLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimetableEditor project file.
        /// </summary>
        public static string Global_ProjectFiletypeDescription {
            get {
                return ResourceManager.GetString("Global.ProjectFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgroup.
        /// </summary>
        public static string Global_Subgroup {
            get {
                return ResourceManager.GetString("Global.Subgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Global_Teacher {
            get {
                return ResourceManager.GetString("Global.Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GroupEdit_DeleteSubgroup {
            get {
                return ResourceManager.GetString("GroupEdit.DeleteSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GroupEdit_Description {
            get {
                return ResourceManager.GetString("GroupEdit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string GroupEdit_Groups_Basics {
            get {
                return ResourceManager.GetString("GroupEdit.Groups.Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgroups.
        /// </summary>
        public static string GroupEdit_Groups_Subgroups {
            get {
                return ResourceManager.GetString("GroupEdit.Groups.Subgroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this subgroup. This operation is irreversible. Subgroup will be unassigned for all groups..
        /// </summary>
        public static string GroupEdit_Message_SubgroupDelete {
            get {
                return ResourceManager.GetString("GroupEdit.Message.SubgroupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GroupEdit_Name {
            get {
                return ResourceManager.GetString("GroupEdit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subgroup name.
        /// </summary>
        public static string GroupEdit_NewSubgroupLabel {
            get {
                return ResourceManager.GetString("GroupEdit.NewSubgroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgroups.
        /// </summary>
        public static string GroupEdit_Subgroups {
            get {
                return ResourceManager.GetString("GroupEdit.Subgroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name.
        /// </summary>
        public static string Main_Errors_ClassName {
            get {
                return ResourceManager.GetString("Main.Errors.ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Main_Errors_Day {
            get {
                return ResourceManager.GetString("Main.Errors.Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Main_Errors_Description {
            get {
                return ResourceManager.GetString("Main.Errors.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string Main_Errors_Slot {
            get {
                return ResourceManager.GetString("Main.Errors.Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Main_Errors_Source {
            get {
                return ResourceManager.GetString("Main.Errors.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is loaded. Do you want to save?.
        /// </summary>
        public static string Main_Message_SaveCurrentProject {
            get {
                return ResourceManager.GetString("Main.Message.SaveCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Main_Ribbon_Edit {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoschedule all unscheduled classes.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following classes could not be scheduled.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule_Message_FollowingClassesCouldNotBeScheduled {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule.Message.FollowingClassesCouldNotBeSchedul" +
                        "ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule_Message_More {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule.Message.More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no unscheduled classes.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule_Message_NoUnscheduledClasses {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule.Message.NoUnscheduledClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully scheduled classes.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule_Message_SuccessfullyScheduled {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule.Message.SuccessfullyScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule_Message_UnitClassroom {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule.Message.UnitClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule_Message_UnitGroup {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule.Message.UnitGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Main_Ribbon_Edit_Timetable_Autoschedule_Message_UnitTeacher {
            get {
                return ResourceManager.GetString("Main.Ribbon.Edit.Timetable.Autoschedule.Message.UnitTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Main_Ribbon_Export {
            get {
                return ResourceManager.GetString("Main.Ribbon.Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        public static string Main_Ribbon_Export_Timetable {
            get {
                return ResourceManager.GetString("Main.Ribbon.Export.Timetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string Main_Ribbon_Export_Timetable_HTML {
            get {
                return ResourceManager.GetString("Main.Ribbon.Export.Timetable.HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string Main_Ribbon_Export_Timetable_PDF {
            get {
                return ResourceManager.GetString("Main.Ribbon.Export.Timetable.PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLS.
        /// </summary>
        public static string Main_Ribbon_Export_Timetable_XLS {
            get {
                return ResourceManager.GetString("Main.Ribbon.Export.Timetable.XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Main_Ribbon_File {
            get {
                return ResourceManager.GetString("Main.Ribbon.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Main_Ribbon_File_New {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Main_Ribbon_File_New_New {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.New.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Main_Ribbon_File_Open {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Main_Ribbon_File_Open_Open {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Open.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open recent.
        /// </summary>
        public static string Main_Ribbon_File_Open_OpenRecent {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Open.OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Main_Ribbon_File_Save {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Main_Ribbon_File_Save_Save {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Save.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string Main_Ribbon_File_Save_SaveAs {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Save.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Main_Ribbon_Project {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Main_Ribbon_Project_Import {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import classrooms.
        /// </summary>
        public static string Main_Ribbon_Project_Import_ImportClassrooms {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.Import.ImportClassrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Main_Ribbon_Project_New {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New class.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewClass {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New classroom.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewClassroom {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewGroup {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subgroup.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewSubgroup {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New teacher.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewTeacher {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_Ribbon_Project_Settings {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string Main_Ribbon_Project_Settings_ProjectSettings {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.Settings.ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms.
        /// </summary>
        public static string Main_Treeview_Classrooms {
            get {
                return ResourceManager.GetString("Main.Treeview.Classrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit classroom.
        /// </summary>
        public static string Main_Treeview_Classrooms_ContextMenu_Edit {
            get {
                return ResourceManager.GetString("Main.Treeview.Classrooms.ContextMenu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this classroom. This operation is irreversible. Classroom will be unassigned for all classes..
        /// </summary>
        public static string Main_Treeview_Classrooms_Message_Remove {
            get {
                return ResourceManager.GetString("Main.Treeview.Classrooms.Message.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit timetable.
        /// </summary>
        public static string Main_Treeview_ContextMenu_EditTimetable {
            get {
                return ResourceManager.GetString("Main.Treeview.ContextMenu.EditTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Main_Treeview_ContextMenu_Remove {
            get {
                return ResourceManager.GetString("Main.Treeview.ContextMenu.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Main_Treeview_Groups {
            get {
                return ResourceManager.GetString("Main.Treeview.Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group.
        /// </summary>
        public static string Main_Treeview_Groups_ContextMenu_Edit {
            get {
                return ResourceManager.GetString("Main.Treeview.Groups.ContextMenu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this group. This operation is irreversible. Group will be unassigned for all classes..
        /// </summary>
        public static string Main_Treeview_Groups_Message_Remove {
            get {
                return ResourceManager.GetString("Main.Treeview.Groups.Message.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this subgroup. This operation is irreversible. Subgroup will be unassigned for all groups and classes..
        /// </summary>
        public static string Main_Treeview_Subgroups_Message_Remove {
            get {
                return ResourceManager.GetString("Main.Treeview.Subgroups.Message.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string Main_Treeview_Teachers {
            get {
                return ResourceManager.GetString("Main.Treeview.Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit teacher.
        /// </summary>
        public static string Main_Treeview_Teachers_ContextMenu_Edit {
            get {
                return ResourceManager.GetString("Main.Treeview.Teachers.ContextMenu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this teacher. This operation is irreversible. Teacher will be unassigned for all classes..
        /// </summary>
        public static string Main_Treeview_Teachers_Message_Remove {
            get {
                return ResourceManager.GetString("Main.Treeview.Teachers.Message.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageBox_Information {
            get {
                return ResourceManager.GetString("MessageBox.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBox_Question {
            get {
                return ResourceManager.GetString("MessageBox.Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBox_Warning {
            get {
                return ResourceManager.GetString("MessageBox.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ProjectSettings_Author {
            get {
                return ResourceManager.GetString("ProjectSettings.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string ProjectSettings_Basics {
            get {
                return ResourceManager.GetString("ProjectSettings.Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string ProjectSettings_Days {
            get {
                return ResourceManager.GetString("ProjectSettings.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProjectSettings_Description {
            get {
                return ResourceManager.GetString("ProjectSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string ProjectSettings_Hours {
            get {
                return ResourceManager.GetString("ProjectSettings.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the class have to be higher than 0 minutes.
        /// </summary>
        public static string ProjectSettings_Message_FromHigherThanTo {
            get {
                return ResourceManager.GetString("ProjectSettings.Message.FromHigherThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot collide with another slot.
        /// </summary>
        public static string ProjectSettings_Message_SlotCollision {
            get {
                return ResourceManager.GetString("ProjectSettings.Message.SlotCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectSettings_Name {
            get {
                return ResourceManager.GetString("ProjectSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable model.
        /// </summary>
        public static string ProjectSettings_TimetableModel {
            get {
                return ResourceManager.GetString("ProjectSettings.TimetableModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom editing.
        /// </summary>
        public static string Tabs_ClassroomEdit {
            get {
                return ResourceManager.GetString("Tabs.ClassroomEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to HTML.
        /// </summary>
        public static string Tabs_ExportHTML {
            get {
                return ResourceManager.GetString("Tabs.ExportHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group editing.
        /// </summary>
        public static string Tabs_GroupEdit {
            get {
                return ResourceManager.GetString("Tabs.GroupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import classrooms.
        /// </summary>
        public static string Tabs_ImportClassroom {
            get {
                return ResourceManager.GetString("Tabs.ImportClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string Tabs_ProjectSettings {
            get {
                return ResourceManager.GetString("Tabs.ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher editing.
        /// </summary>
        public static string Tabs_TeacherEdit {
            get {
                return ResourceManager.GetString("Tabs.TeacherEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable editing.
        /// </summary>
        public static string Tabs_TimetableEdit {
            get {
                return ResourceManager.GetString("Tabs.TimetableEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Tabs_Welcome {
            get {
                return ResourceManager.GetString("Tabs.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string TeacherEdit_Days {
            get {
                return ResourceManager.GetString("TeacherEdit.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TeacherEdit_Description {
            get {
                return ResourceManager.GetString("TeacherEdit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability hours.
        /// </summary>
        public static string TeacherEdit_Groups_AvailabilityHours {
            get {
                return ResourceManager.GetString("TeacherEdit.Groups.AvailabilityHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string TeacherEdit_Groups_Basics {
            get {
                return ResourceManager.GetString("TeacherEdit.Groups.Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string TeacherEdit_Hours {
            get {
                return ResourceManager.GetString("TeacherEdit.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;From&quot; value is higher or equal to &quot;To&quot; value.
        /// </summary>
        public static string TeacherEdit_Message_FromHigherThanTo {
            get {
                return ResourceManager.GetString("TeacherEdit.Message.FromHigherThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour collide with another hour.
        /// </summary>
        public static string TeacherEdit_Message_HourCollision {
            get {
                return ResourceManager.GetString("TeacherEdit.Message.HourCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TeacherEdit_Name {
            get {
                return ResourceManager.GetString("TeacherEdit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoschedule.
        /// </summary>
        public static string TimetableEditor_Autoschedule {
            get {
                return ResourceManager.GetString("TimetableEditor.Autoschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscheduled.
        /// </summary>
        public static string TimetableEditor_Unscheduled {
            get {
                return ResourceManager.GetString("TimetableEditor.Unscheduled", resourceCulture);
            }
        }
    }
}
