//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetableDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimetableDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string ClassroomEdit_Capacity {
            get {
                return ResourceManager.GetString("ClassroomEdit.Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is limited?.
        /// </summary>
        public static string ClassroomEdit_CapacityIsLimited {
            get {
                return ResourceManager.GetString("ClassroomEdit.CapacityIsLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ClassroomEdit_Description {
            get {
                return ResourceManager.GetString("ClassroomEdit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClassroomEdit_Name {
            get {
                return ResourceManager.GetString("ClassroomEdit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New classroom.
        /// </summary>
        public static string Global_DefaultClassroomName {
            get {
                return ResourceManager.GetString("Global.DefaultClassroomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string Global_DefaultProjectName {
            get {
                return ResourceManager.GetString("Global.DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no project loaded.
        /// </summary>
        public static string Global_NoProjectLoadedTitle {
            get {
                return ResourceManager.GetString("Global.NoProjectLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is loaded. Do you want to save?.
        /// </summary>
        public static string Main_Message_SaveCurrentProject {
            get {
                return ResourceManager.GetString("Main.Message.SaveCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Main_Ribbon_File {
            get {
                return ResourceManager.GetString("Main.Ribbon.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New/Open.
        /// </summary>
        public static string Main_Ribbon_File_NewOpen {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.NewOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Main_Ribbon_File_NewOpen_New {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.NewOpen.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Main_Ribbon_File_NewOpen_Open {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.NewOpen.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open recent.
        /// </summary>
        public static string Main_Ribbon_File_NewOpen_OpenRecent {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.NewOpen.OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Main_Ribbon_File_Save {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Main_Ribbon_File_Save_Save {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Save.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string Main_Ribbon_File_Save_SaveAs {
            get {
                return ResourceManager.GetString("Main.Ribbon.File.Save.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Main_Ribbon_Project {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Main_Ribbon_Project_New {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New class.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewClass {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New classroom.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewClassroom {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewGroup {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subgroup.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewSubgroup {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New teacher.
        /// </summary>
        public static string Main_Ribbon_Project_New_NewTeacher {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.New.NewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_Ribbon_Project_Settings {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string Main_Ribbon_Project_Settings_ProjectSettings {
            get {
                return ResourceManager.GetString("Main.Ribbon.Project.Settings.ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms.
        /// </summary>
        public static string Main_Treeview_Classrooms {
            get {
                return ResourceManager.GetString("Main.Treeview.Classrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit classroom.
        /// </summary>
        public static string Main_Treeview_Classrooms_ContextMenu_Edit {
            get {
                return ResourceManager.GetString("Main.Treeview.Classrooms.ContextMenu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit timetable.
        /// </summary>
        public static string Main_Treeview_ContextMenu_EditTimetable {
            get {
                return ResourceManager.GetString("Main.Treeview.ContextMenu.EditTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Main_Treeview_ContextMenu_Remove {
            get {
                return ResourceManager.GetString("Main.Treeview.ContextMenu.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ProjectSettings_Author {
            get {
                return ResourceManager.GetString("ProjectSettings.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string ProjectSettings_Basics {
            get {
                return ResourceManager.GetString("ProjectSettings.Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string ProjectSettings_Days {
            get {
                return ResourceManager.GetString("ProjectSettings.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProjectSettings_Description {
            get {
                return ResourceManager.GetString("ProjectSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string ProjectSettings_Hours {
            get {
                return ResourceManager.GetString("ProjectSettings.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the class have to be higher than 0 minutes.
        /// </summary>
        public static string ProjectSettings_Message_FromHigherThanTo {
            get {
                return ResourceManager.GetString("ProjectSettings.Message.FromHigherThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot collide with another slot.
        /// </summary>
        public static string ProjectSettings_Message_SlotCollision {
            get {
                return ResourceManager.GetString("ProjectSettings.Message.SlotCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectSettings_Name {
            get {
                return ResourceManager.GetString("ProjectSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable model.
        /// </summary>
        public static string ProjectSettings_TimetableModel {
            get {
                return ResourceManager.GetString("ProjectSettings.TimetableModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom editing.
        /// </summary>
        public static string Tabs_ClassroomEdit {
            get {
                return ResourceManager.GetString("Tabs.ClassroomEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string Tabs_ProjectSettings {
            get {
                return ResourceManager.GetString("Tabs.ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Tabs_Welcome {
            get {
                return ResourceManager.GetString("Tabs.Welcome", resourceCulture);
            }
        }
    }
}
